name: 'FAF TAF Action'
description: 'Automatically update .taf (Testing Activity Feed) files with test results'
author: 'wolfejam'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  test-output-file:
    description: 'Path to file containing test output (created by previous step)'
    required: true

  auto-commit:
    description: 'Automatically commit .taf updates (default: true)'
    required: false
    default: 'true'

  commit-message:
    description: 'Custom commit message for .taf updates'
    required: false
    default: 'chore(taf): update .taf receipt [skip ci]'

outputs:
  result:
    description: 'Test result (PASSED, FAILED, IMPROVED, DEGRADED)'

  passed:
    description: 'Number of tests passed'

  failed:
    description: 'Number of tests failed'

  total:
    description: 'Total number of tests'

  taf-updated:
    description: 'Whether .taf file was updated (true/false)'

runs:
  using: 'node20'
  main: 'dist/index.js'
